services:
  api:
    image: cronchat-api:latest
    ports:
      - "5555:5555"
    volumes:
      - ./data/user_avatars:/app/data/user_avatars
      - ./data/chat_uploads:/app/data/chat_uploads
    environment:
      - AVATAR_DIR=/app/data/user_avatars
      - CHAT_UPLOAD_DIR=/app/data/chat_uploads
